version: '3.4'
services:
  web:
    image: nginx:1.25.2-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./containers/web/default.conf:/etc/nginx/conf.d/default.conf:ro
  react:
    build:
      context: .
      dockerfile: ./containers/react/Dockerfile
      target: development
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./:/app
    environment:
      WDS_SOCKET_PORT: ${HOST_PORT:-3000}
      REACT_APP_HOST_URL: ${HOST_URL:-http://localhost:3000}
  storybook:
    build:
      context: .
      dockerfile: ./containers/react/Dockerfile
      target: storybook
    ports:
      - "${STORYBOOK_PORT:-6006}:6006"
    volumes:
      - ./:/app
