version: '3.4'
services:
  react:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    entrypoint: sh -c "yarn install&&yarn start"
volumes:
  node_modules:
