version: '3.8'

x-app: &app
  build:
    context: .
    dockerfile: ./containers/react/Dockerfile
  volumes:
    - .:/app
    - node_modules:/app/node_modules

services:
  web:
    image: nginx:1.25.2-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./containers/web/default.conf:/etc/nginx/conf.d/default.conf:ro

  react:
    <<: *app
    build:
      target: development
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      WDS_SOCKET_PORT: ${HOST_PORT:-3000}
      REACT_APP_HOST_URL: ${HOST_URL:-http://localhost:3000}

  storybook:
    <<: *app
    build:
      target: storybook
    ports:
      - "${STORYBOOK_PORT:-6006}:6006"

volumes:
  node_modules:
