version: '3.4'
services:
  react:
    image: node:16.20-buster-slim
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    entrypoint: sh -c "yarn install&&yarn start"
volumes:
  node_modules:
