version: '3.4'
services:
  react:
    image: node:16.20-buster-slim
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "yarn install&&yarn start"
    environment:
      WDS_SOCKET_PORT: ${HOST_PORT:-3000}
volumes:
  node_modules:
