version: '3.9'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./openapi.yml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  mock:
    image: stoplight/prism:5
    command: 'mock -h 0.0.0.0 /tmp/openapi.yaml'
    volumes:
      - ./openapi.yml:/tmp/openapi.yaml:ro
    ports:
      - '4010:4010'
